version: 0.2

phases:
  install:
    runtime-versions:
       nodejs: 10

  build:
    commands:
      - cd $CODEBUILD_SRC_DIR_source1
      - touch file2
      - cd $CODEBUILD_SRC_DIR_source2
      - touch file2
 
artifacts:
  base-directory: $CODEBUILD_SRC_DIR_source1
  files:
     - file1
     - file2

  secondary-artifacts:
    artifact2:
      base-directory: $CODEBUILD_SRC_DIR_source2
      files:
        - file1 
        - file2

