version: 0.2

phases:
  install:
    runtime-versions:
       nodejs: 10

  build:
    commands:
      - cd $CODEBUILD_SRC_DIR_source1
      - touch file2
      - ls
      - cd $CODEBUILD_SRC_DIR_source2
      - touch file2
      - ls
      - cd $FOLDER1
      - ls
 
artifacts:
  #base-directory: $CODEBUILD_SRC_DIR_source1
  files:
     - file1  

  secondary-artifacts:
    artifact2:
      base-directory: $CODEBUILD_SRC_DIR_source2
      files:
        - file1 
        - file2
        - $FOLDER1/file3

